services:
  app:
    build: .
    container_name: audio_download_service
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    env_file:
      - .env
    command: ["uvicorn", "audio_download_service.main:app", "--host", "0.0.0.0", "--port", "8000", "--reload"]
    depends_on:
      - db

  db:
    image: postgres:16
    container_name: postgres-16
    restart: always
    ports:
      - "5432:5432"
    env_file:
      - .env
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
